### ISSUE TITLE
Which bible is which?

### ISSUE THREAD

**Issue by codeananda** [omarciovsena/abibliadigital#403]
I couldn't find anywhere in the documentation saying what the abbreviations mean. Posting explanations here to help future users who were also confused. 

### English Language
* "acf" stands for "American Correctional Facility," which is a version of the Bible specifically adapted for use in correctional facilities.
* "apee" represents the "American Public Education Edition," which is a version of the Bible tailored for public education and aimed at meeting the legal requirements for public school distribution.
* "bbe" stands for the "Bible in Basic English," which is a simplified English translation of the Bible, designed to make the text more accessible to non-native English speakers.
* "kjv" refers to the "King James Version," which is one of the most well-known and widely used English translations of the Bible. It was originally published in 1611 and remains highly regarded for its literary and historical significance.

### Spanish Language
* "nvi" represents the "Nueva Versión Internacional," which is a Spanish translation of the Bible that aims to convey the message of the original biblical texts in clear and contemporary language.
* "ra" stands for the "Reina-Valera," which is a Spanish translation of the Bible widely used among Spanish-speaking Protestant Christians.
* "rvr" refers to the "Reina-Valera Revision," which is an updated version of the Reina-Valera Bible, incorporating revisions and improvements to the original translation.

Not sure how this corresponds to 4 languages though as you say on the homepage?

**Comment by alexandrecoura96** [comment]
In portuguese = acf, nvi, ra
In english = bbe, kjv
In french = apee
In Spanish = rvr
That's all version, with 4 different languages. And Acf stands for "Almeida Corrigida Fiel" @codeananda

**Comment by MikeyA-yo** [comment]
how do i know the books
of the bible like in portugal i saw sl for psalms
