### ISSUE TITLE
Permitir buscas por palavras sem camelcase e desconsiderar acentuações

### ISSUE THREAD

**Issue by EdnezerRezende** [omarciovsena/abibliadigital#412]
**Describe the bug**
Ao executar, devemos informar exatamente a palavra com acentuação ou camelcase pois do contrário, irá trazer resultado não encontrado.
Por exemplo, ao pesquisar pelo nome de pessoa como "**Acsa**", ele me trará algumas ocorrências, porém se eu colocar como "acsa" (minúsculo), ele não encontra, inclusive se eu colocar partes de frases também é da mesma forma, tenho que colocar a frase toda ("No princí" não encontra, porém "No princípio" encontra) e o mesmo vale para palavras acentuadas como princípio, se enviar sem o acento, também não encontra.
_When running, we must inform exactly the word with accents or camelcase, otherwise it will return a result not found.
For example, when searching for a person's name like "**Acsa**", it will bring me some occurrences, but if I put it as "acsa" (lowercase), it doesn't find it, even if I put parts of phrases, it's also the same In the same way, I have to put the whole sentence ("No princi" can't find it, but "No principio" can find it) and the same goes for words accented as a principle, if you send it without the accent, it won't find it either._

**To Reproduce**
Utilizando o Resource: POST https://www.abibliadigital.com.br/api/verses/search .
Por exemplo, ao pesquisar pelo nome de pessoa como "**Acsa**", ele me trará algumas ocorrências, porém se eu colocar como "acsa" (minúsculo), ele não encontra, inclusive se eu colocar partes de frases também é da mesma forma, tenho que colocar a frase toda ("No princí" não encontra, porém "No princípio" encontra) e o mesmo vale para palavras acentuadas como princípio, se enviar sem o acento, também não encontra.
_Using Resource: POST https://www.abibliadigital.com.br/api/verses/search .
For example, when searching for a person's name like "**Acsa**", it will bring me some occurrences, but if I put it as "acsa" (lowercase), it doesn't find it, even if I put parts of phrases, it's also the same In the same way, I have to put the whole sentence ("No princi" can't find it, but "No principio" can find it) and the same goes for words accented as a principle, if you send it without the accent, it won't find it either._

**Expected behavior**
Espera-se que qualquer forma que ocorrer a busca, o resultado será o mesmo, ou seja, pesquisando princípio ou principio, acsa ou Acsa, No princí ou no princi, traga os mesmos resultados.
It is expected that whatever way the search occurs, the result will be the same, that is, searching for principle or principle, acsa or Acsa, In principle or in principle, will bring the same results.

**Comment by rubenslpdev** [comment]
Vocês têm alguma previsão para a solução desse problema?

**Comment by Pablo87996** [comment]
Vou tentar resolver esse problema e fazer um pull request.
