### ISSUE TITLE
Getting MongoError 8000 when creating User

### ISSUE THREAD

**Issue by emidiomatheus** [omarciovsena/abibliadigital#417]
I'm receiving this message when call the endpoint to create user

`{
    "msg": "Oops! An unexpected error has occurred, create an [issue](https://github.com/omarciovsena/abibliadigital/issues/new) with the information of this request.",
    "err": {
        "ok": 0,
        "code": 8000,
        "codeName": "AtlasError",
        "name": "MongoError"
    }
}`

**Comment by GBellmont** [comment]
When do you intend to solve this problem?

**Comment by omarciovsena** [comment]
@emidiomatheus thanks for the contribution, adjustment made in https://github.com/omarciovsena/abibliadigital/commit/df228b6bccf8e37ada43be87c984453b1ab17ed9
