### ISSUE TITLE
Erro ao criar usuário

### ISSUE THREAD

**Issue by RicardoPetter** [omarciovsena/abibliadigital#418]
**Describe the bug**
Ao tentar criar um novo usuário, está retornando um erro do banco mongo.db

**To Reproduce**
1) Crio uma requisição do tipo post no Insomnia para a rota: https://www.abibliadigital.com.br/api/users
2) Preencho o header com os cabeçalhos informados na documentação:
 { 
    'Accept': 'application/json',
    'Content-Type': 'application/json'
  }
3) No body da requição, uso o json sugerido pela documentação
{
  "name": "Meu nome",
  "email": "meuemail@gmail.com",
  "password": "minha senha com no mínimo 6 caracteres", 
  "notifications": true 
}

**Expected behavior**
Era pra retornar um objeto no  body do tipo:
{
  "name": "Name",
  "email": "email@email.com",
  "password": "102030", // minimum size 6 digits
  "notifications": true // receive update emails from www.abibliadigital.com.br
} 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Insomnia 
 - Version [2023.5.8]

**Additional context**
Erro apresentado
{
	"msg": "Oops! An unexpected error has occurred, create an [issue](https://github.com/omarciovsena/abibliadigital/issues/new) with the information of this request.",
	"err": {
		"ok": 0,
		"code": 8000,
		"codeName": "AtlasError",
		"name": "MongoError"
	}
}

**Comment by GBellmont** [comment]
When do you intend to solve this problem?

**Comment by omarciovsena** [comment]
@RicardoPetter obrigado pela contribuição, ajuste realizado em https://github.com/omarciovsena/abibliadigital/commit/df228b6bccf8e37ada43be87c984453b1ab17ed9
