### ISSUE TITLE
Opa, parece estar ocorrendo algo no processo de criação de usuário...

### ISSUE THREAD

**Issue by GBellmont** [omarciovsena/abibliadigital#419]
![image](https://github.com/omarciovsena/abibliadigital/assets/61256397/cfd8069b-8816-4a9d-8e2c-650f9746e0c0)

**Request**
{
    "name": "luanCasado",
    "email": "luan.barcella@gmail.com",
    "password": "123456", //Mínimo de 6 dígitos
    "notifications": true
}

**Response**
{
    "msg": "Oops! An unexpected error has occurred, create an [issue](https://github.com/omarciovsena/abibliadigital/issues/new) with the information of this request.",
    "err": {
        "ok": 0,
        "code": 8000,
        "codeName": "AtlasError",
        "name": "MongoError"
    }
}

**Comment by omarciovsena** [comment]
@GBellmont, muito obrigado pela contribuição. 

Correção realizada no commit https://github.com/omarciovsena/abibliadigital/commit/df228b6bccf8e37ada43be87c984453b1ab17ed9
