### ISSUE TITLE
Falta informações de como fazer login no readme.md

### ISSUE THREAD

**Issue by valdirsantos714** [omarciovsena/abibliadigital#442]
Falta informações de como fazer login no readme.md, como posso saber como me autenticar para poder usar a api gratuitamente e ilimitadamente?

**Comment by gustavovni08** [comment]
estou com o mesmo problema por aqui, criei meu usuário mas não sei como logar para usar ele de forma ilimitada

**Comment by JamilFilho** [comment]
Para autenticar o usuário ao fazer a requisição você precisa passar no Header da requisição o valor do token que é gerado ao criar um novo usuário como Authorization: Bearer. Por exemplo:

```
// JavaScript fetch
const myHeaders = new Headers();
myHeaders.append("Authorization", "Bearer <seu token>");

const requestOptions = {
  method: "GET",
  headers: myHeaders,
  redirect: "follow"
};

fetch("https://www.abibliadigital.com.br/<endpoint>", requestOptions)
  .then((response) => response.text())
  .then((result) => console.log(result))
  .catch((error) => console.error(error));
```
