### ISSUE TITLE
Erro para criar usuário pela API

### ISSUE THREAD

**Issue by HenriqueDev7** [omarciovsena/abibliadigital#449]
{
    "msg": "Oops! An unexpected error has occurred, create an [issue](https://github.com/omarciovsena/abibliadigital/issues/new) with the information of this request.",
    "err": {
        "ok": 0,
        "code": 8000,
        "codeName": "AtlasError",
        "name": "MongoError"
    }
}

**Comment by omarciovsena** [comment]
@HenriqueDev7 já resolvemos esse problema, tente novamente por favor. 

`curl --location 'https://www.abibliadigital.com.br/api/users/' \
--header 'Content-Type: application/json' \
--data-raw '{
	"name": "Nome",
	"email": "email@email.com",
	"password": "XYZ",
	"notifications": true
}'`

**Comment by omarciovsena** [comment]
@HenriqueDev7 já resolvemos esse problema, tente novamente por favor.

`curl --location 'https://www.abibliadigital.com.br/api/users/' \ --header 'Content-Type: application/json' \ --data-raw '{ "name": "Nome", "email": "email@email.com", "password": "XYZ", "notifications": true }'`
