### ISSUE TITLE
Erro ao Tentar quaquer requisição

### ISSUE THREAD

**Issue by Ismael-g5** [omarciovsena/abibliadigital#460]
{
msg: "Oops! An unexpected error has occurred, create an [issue](https://github.com/omarciovsena/abibliadigital/issues/new) with the information of this request.",
[err](https://www.abibliadigital.com.br/): {
command: "GET",
code: "NR_CLOSED",
[args](https://www.abibliadigital.com.br/): [
"meu_ip"
]
}
}

**Comment by RICARDO3TALENTOS** [comment]
estou enfrentando o mesmo erro. voce conseguiu resolver?

**Comment by Ismael-g5** [comment]
Sim, é só criar o usuário,  tem explicando o processo na doc

Em ter., 22 de out. de 2024, 16:41, RICARDO3TALENTOS <
***@***.***> escreveu:

**Comment by Ismael-g5** [comment]
https://github.com/omarciovsena/abibliadigital/blob/master/DOCUMENTATION.md

Em ter., 22 de out. de 2024, 22:58, Ismael Guedes <
***@***.***> escreveu:
