### ISSUE TITLE
Rest API error

### ISSUE THREAD

**Issue by DaviJP7** [omarciovsena/abibliadigital#469]
**Endpoint**: https://www.abibliadigital.com.br/api/verses/acf/random
**Response**: 
```
{
  "msg": "Oops! An unexpected error has occurred, create an [issue](https://github.com/omarciovsena/abibliadigital/issues/new) with the information of this request.",
  "err": {
    "command": "GET",
    "code": "NR_CLOSED",
    "args": [
      "177.24.240.163"
    ]
  }
}
```

**Comment by JamilFilho** [comment]
Para resolver esse erro você precisa realizar a requisição com token de autenticação [conforme a documentação.](https://github.com/omarciovsena/abibliadigital/blob/master/DOCUMENTATION.md#users)
