### ISSUE TITLE
Gostaria de usar a api de vocês, mas n encontrei como posso utilizar o token ou mesmo sem ele n consigo

### ISSUE THREAD

**Issue by GeorgeNicacio** [omarciovsena/abibliadigital#471]

**Comment by omarciovsena** [comment]
@GeorgeNicacio faltam informações básicas na issue. Coloque uma descrição para ficar mais clara. Se preferir utilize a comunidade para tirar as dúvidas, estamos sempre por lá. https://chat.whatsapp.com/D6u9LuqgKYHJwJXCnneXpH
